# frozen_string_literal: true

source "https://rubygems.org"

group :development do
  # 中略
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
end

# gem "rails"
