INSERT INTO programs (program_title, program_detail)
VALUES
('Comedy Central', 'Laugh out loud with the best comedy sketches and stand-up performances.'),
('Action Unlimited', 'Non-stop adrenaline-pumping action movies and TV series.'),
('Romantic Escapes', 'Join us as we explore the most beautiful and romantic destinations around the globe.'),
('Mystery Files', 'Delve into unsolved mysteries and intriguing crime cases with expert investigators.'),
('Science World', 'Discover the wonders of science through exciting experiments and fascinating documentaries.'),
('Horror Nightmares', 'Get ready for a spine-chilling night of horror movies that will leave you terrified.'),
('Adventure Quest', 'Embark on thrilling adventures in the wilderness and uncover hidden treasures.'),
('Animation Mania', 'Enjoy a marathon of your favorite animated shows and movies for all ages.'),
('Crime Watch', 'Stay updated on the latest crime news and investigations happening in your city.'),
('Travel Diaries', 'Join our hosts as they explore breathtaking destinations and share their travel experiences.'),
('Documentary Showcase', 'Experience captivating documentaries that cover a wide range of subjects and issues.'),
('Reality TV Showdown', 'Witness intense competitions and dramatic moments in the world of reality television.'),
('Game Show Extravaganza', 'Test your knowledge and skills as contestants battle it out for fantastic prizes.'),
('Talk Show Live', 'Engage in thought-provoking discussions and interviews with renowned guests.'),
('Variety Funhouse', 'Be entertained with a mix of music, comedy, and exciting performances.'),
('Sports Unlimited', 'Catch all the thrilling sports action and highlights from around the world.'),
('World News Tonight', 'Stay informed with comprehensive coverage of the day top news stories.'),
('Music Fusion', 'Experience a fusion of different music genres and performances from talented artists.'),
('Fashion Forward', 'Explore the latest trends, styles, and fashion tips from the world of haute couture.'),
('Historical Journey', 'Take a journey through time as we delve into significant historical events and figures.'),
('Supernatural Encounters', 'Explore the world of the supernatural and paranormal with firsthand accounts.'),
('Family Fun Time', 'Enjoy quality family programming with wholesome shows and entertainment.'),
('Western Classics', 'Relive the golden era of Western movies and TV series featuring iconic cowboys.'),
('Sci-Fi Spectacular', 'Immerse yourself in the world of futuristic technology and thrilling science fiction.'),
('Culinary Delights', 'Indulge in mouthwatering recipes, culinary adventures, and gourmet delights.'),
('Globe Trekker', 'Embark on unforgettable journeys to exotic locations and experience different cultures.'),
('Educational Explorers', 'Learn fascinating facts and expand your knowledge through educational programming.'),
('Musical Melodies', 'Get lost in a melodic journey with enchanting music performances and live concerts.'),
('Fashion Runway', 'Witness the glamour and creativity of fashion as models strut the runway in stunning designs.');
